name: Github Action Demo
run-name: ${{ github.actor}} Demo

on: [push]

jobs: 
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Run a one-line script
              run: echo Hello, world!

            - name: Run a multi-line script
              run: |
                echo Hello, world!
                echo This is a multi-line script.









