name: Github Action Demo
run-name: ${{ github.actor}} Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Hello, world!
          echo This is a multi-line script.

  test-and-build:
    runs-on: ubuntu-latest
    needs: hello-world # This job waits for hello-world to complete

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: 🧪 Run tests
        run: node test.js

      - name: 📊 Test results
        run: echo "✅ All tests passed successfully!"

  slack-notification:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: always() # This ensures the job runs even if previous jobs fail

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📢 Notify Slack on Success
        if: needs.test-and-build.result == 'success'
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: "#github-actions" # Replace with your Slack channel
          text: |
            ✅ *Workflow Completed Successfully!*
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Actor: ${{ github.actor }}

            All tests passed and build completed successfully! 🎉
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"

      - name: 📢 Notify Slack on Failure
        if: needs.test-and-build.result == 'failure'
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: "#github-actions" # Replace with your Slack channel
          text: |
            ❌ *Workflow Failed!*
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Actor: ${{ github.actor }}

            Please check the workflow logs for details.
        env:
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
