name: Github Action Demo
run-name: ${{ github.actor}} Demo

on: [push]

jobs: 
  hello-world:
      runs-on: ubuntu-latest
      steps:
          - name: Run a one-line script
            run: echo Hello, world!

          - name: Run a multi-line script
            run: |
              echo Hello, world!
              echo This is a multi-line script.

  test-and-build:
    runs-on: ubuntu-latest
    needs: hello-world  # This job waits for hello-world to complete
    
    steps:
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: 🧪 Run tests
        run: node test.js
      
      - name: 📊 Test results
        run: echo "✅ All tests passed successfully!"

